### ISSUE TITLE
Add Volume bar and Settings button to the quick setting

### ISSUE THREAD

**Issue by Naragorn** [EuCaue/gnome-shell-extension-quick-lofi#4]
Hi, can you add a volume bar to the top bar quick setting menu?

Additionally, can you add a button to the top bar quick setting which opens the extension setting?

**Comment by EuCaue** [comment]
> Hi, can you add a volume bar to the top bar quick setting menu?

Yep, that’s next on my to-do list! :) I’ll be adding a way to change the **volume without having to open the preferences** page.

> Additionally, can you add a button to the top bar quick setting which opens the extension setting?

Now that you mention it, I completely forgot to mention that right-clicking opens the extension settings. Sorry about that! 😅

By the way, when you say quick settings, do you mean the quick settings panel where the Wi-Fi/volume controls are, or the menu bar itself?

Thank you for using the extension!

**Comment by Naragorn** [comment]
That's cool! I meant the menu bar, sorry.

**Comment by EuCaue** [comment]
**Added** **on** 431117072792220647c9254a2298f3f8ea33a7cb. 

Closing this! =D
